---
title: "Weekly Lesson Plan"
execute: 
  freeze: true
editor: visual
---

| Week | Date       | Topic                                                                             | Student Assignment        |
|------------------|------------------|-------------------|------------------|
| 1    | 26/8/2024  | [Introduction to Geospatial Analytics](outline/Lesson01_outline.html)             |                           |
| 2    | 2/9/2024   | [Spatial Point Patterns Analysis (SPAA)](outline/Lesson02_outline.html)           |                           |
| 3    | 9/9/2024   | [Advanced Spatial Point Patterns Analysis](outline/Lesson03_outline.html)         | Take-home Exercise 1 due. |
| 4    | 16/9/2024  | [Spatial Weights and Applications](outline/Lesson04_outline.html)                 |                           |
| 5    | 23/9/2024  | [Global and Local Measures of Spatial Association](outline/Lesson05_outline.html) |                           |
| 6    | 30/9/2024  | [Geographic Segmentation](outline/Lesson06_outline.html)    |                           |
|      | 7/10/2024  |                                                                                   | Take-home Exercise 2 due. |
| 7    | 14/10/2024 | [Geographically Weighted Explanatory Models](outline/Lesson07_outline.html)       |                           |
| 8    | 21/10/2024 | [Geographically Weighted Predictive Models](outline/Lesson08_outline.html)        |                           |
| 9    | 28/10/2024 | [Spatial Interaction Models](outline/Lesson09_outline.html)                       |                           |
| 10   | 4/11/2024  | [Modelling Geographic of Accessibility](outline/Lesson10_outline.html)            | Take-home Exercise 3 due. |
