---
title: "Take-home Exercise 3b: Predicting HDB Resale Prices with Geographically Weighted Machine Learning Methods"
date: "October 1, 2024"
date-modified: "last-modified"
format: html
toc: true
execute: 
  eval: true
  echo: true
  warning: false
  freeze: auto
editor: visual
---

::: callout-important
This handout provides the context, the task, the expectation and the grading criteria of Take-home Exercise 2. Students must review and understand them before getting started with the take-home exercise.
:::

## Setting the Scene

Housing is an essential component of household wealth worldwide. Buying a housing has always been a major investment for most people. The price of housing is affected by many factors. Some of them are global in nature such as the general economy of a country or inflation rate. Others can be more specific to the properties themselves. These factors can be further divided to structural and locational factors. Structural factors are variables related to the property themselves such as the size, fitting, and tenure of the property. Locational factors are variables related to the neighbourhood of the properties such as proximity to childcare centre, public transport service and shopping centre.

Conventional, housing resale prices predictive models were built by using Ordinary Least Square (OLS) method. However, this method failed to take into consideration that spatial autocorrelation and spatial heterogeneity exist in geographic data sets such as housing transactions. With the existence of spatial autocorrelation, the OLS estimation of predictive housing resale pricing models could lead to biased, inconsistent, or inefficient results (Anselin 1998). In view of this limitation, **Geographical Weighted Models** were introduced to better calibrate predictive models for housing resale prices.

## The Task

In this take-home exercise, you are required to calibrate a predictive model to predict HDB resale prices between July-September 2024 by using HDB resale transaction records in 2023.

## The Data

For the purpose of this take-home exercise, **HDB Resale Flat Prices** provided by [**Data.gov.sg**]() should be used as the core data set. The study should focus on either three-room, four-room or five-room flat.

Below is a list of recommended predictors to consider. However, students are free to include other appropriate independent variables.

-   Structural factors
    -   Area of the unit
    -   Floor level
    -   Remaining lease
    -   Age of the unit
    -   Main Upgrading Program (MUP) completed (optional)
-   Locational factors
    -   Proxomity to CBD
    -   Proximity to eldercare
    -   Proximity to foodcourt/hawker centres
    -   Proximity to MRT
    -   Proximity to park
    -   Proximity to good primary school
    -   Proximity to shopping mall
    -   Proximity to supermarket
    -   Numbers of kindergartens within 350m
    -   Numbers of childcare centres within 350m
    -   Numbers of bus stop within 350m
    -   Numbers of primary school within 1km

## Grading Criteria

This exercise will be graded by using the following criteria:

-   **Geospatial Data Wrangling (20 marks):** This is an important aspect of geospatial analytics. You will be assessed on your ability:

    -   to employ appropriate R functions from various R packages specifically designed for modern data science such as readxl, tidyverse (tidyr, dplyr, ggplot2), sf just to mention a few of them, to perform the import and extract the data.
    -   to clean and derive appropriate variables for meeting the analysis need.

::: callout-warning
All data are like vast grassland full of land mines. Your job is to clear those mines and not to step on them.
:::

-   **Geospatial Analysis (30 marks):** In this exercise, you are expected to use conventional multiple linear regression, random forest and geographically weighted random forest methods learned in class to calibrate the predictive models including model comparison. You will be assessed on your ability:

    -   to describe the methods used correctly, and
    -   to provide accurate interpretation of the analysis results.

-   **Geovisualisation and geocommunication (20 marks):** In this section, you will be assessed on your ability to communicate the results in business friendly visual representations. This course is geospatial centric, hence, it is important for you to demonstrate your competency in using appropriate geovisualisation techniques to reveal and communicate the findings of your analysis.

-   **Reproducibility (15 marks):** This is an important learning outcome of this exercise. You will be assessed on your ability to provide a comprehensive documentation of the analysis procedures in the form of code chunks of Quarto. It is important to note that it is not enough by merely providing the code chunk without any explanation on the purpose and R function(s) used.

-   **Bonus (15 marks):** Demonstrate your ability to employ methods beyond what you had learned in class to gain insights from the data.

## Submission Instructions

-   The write-up of the take-home exercise must be in **Quarto html document** format. You are required to publish the write-up on [**Netlify**](https://www.netlify.com/).
-   Zip the take-home exercise folder and upload it onto eLearn. If the size of the zip file is beyond the capacity of eLearn, you can upload it on SMU OneDrive and provide the download link on eLearn..

## Due Date

10th November 2024 (Sunday), 11.59pm (midnight).

## Learning from senior

You are advised to review these sample submissions prepared by your seniors.

## Q & A

Please submit your questions or queries related to this take-home exercise on Piazza.

## Peer Learning

## Reference

- [SpatialML](https://cran.r-project.org/web/packages/SpatialML/index.html)
- [SpatialRF](https://blasbenito.github.io/spatialRF/index.html)

### Research articles

Wang, Shuli et. al. (2024) **"Geographically weighted machine learning for modeling spatial heterogeneity in traffic crash frequency and determinants in US"**, *Accident analysis and prevention*, Vol.199, p.107528-107528, Article 107528. SMU Library e-journal.

Lotfata, Aynaz & Georganos, Stefanos (2023) **"Spatial machine learning for predicting physical inactivity prevalence from socioecological determinants in Chicago, Illinois, USA"**, *Journal of geographical systems*, pp.1-21

Wu, Dongyu ; Zhang, Yingheng ; Xiang, Qiaojun (2024) **"Geographically weighted random forests for macro-level crash frequency prediction"**, *Accident analysis and prevention*, Vol.194, p.107370-107370, Article 107370.





